config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'message', to: 'messages#create'
  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :user
    validates :body, presence: true
    scope :custom_display, -> { order(:created_at).last(20) }
end

app/models/user.rb
class User < ApplicationRecord
    validates :username, presence: true, length: {minimum: 3, maximum: 15},
               uniqueness: {case_sensitive: false}
    has_many :messages
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user, :logged_in?

    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
  
    def logged_in?
      !!current_user
    end
  
    def require_user
      if !logged_in?
        flash[:error] = "You must be logged in to perform that action"
        redirect_to login_path
      end
    end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController 

    before_action :require_user

    def create 
       message = current_user.messages.build(message_params)
       if message.save 
          ActionCable.server.broadcast "chatroom_channel",
                                              mod_message: message_render(message)
       end
    end

    private 
    def message_params 
        params.require(:message).permit(:body)
    end

    def message_render(message)
          render(partial: 'message', locals: {message: message})
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    before_action :require_user

    def home 
        @message = Message.new
        @messages = Message.custom_display

    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController 

    before_action :logged_in_redirect, only: [:new, :create]

    def new 

    end

    def create 
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
        session[:user_id] = user.id 
        flash[:success] = "you have successfully logged in!!" #success and error are the classes we will used to design messages
        redirect_to root_path
    else 
        flash.now[:error] = "There was something wrong with your login information"
        render 'new'
    end
    end

    def destroy 
    session[:user_id] = nil
    flash[:success] = "you have successfully logged out"
    redirect_to login_path
    end

    private

    def logged_in_redirect 
    if logged_in? 
        flash[:error] = "You are already logged in!!"
        redirect_to root_path
    end
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController 

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save 
          session[:user_id] = @user.id
          flash[:success] = "Welome To The Message Me Application #{@user.username}, You Have Successfully Signed Up!!!"
          redirect_to root_path
        else 
          render 'new'
        end
      end

    private
    def user_params
           params.require(:user).permit(:username, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message_content| %>
<div class="ui <%= message_type %> message tansition">
  <i class="close icon"></i>
  <div class="header">
    <%= message_content %>
  </div>
</div>
<%end%>

app/views/layouts/_navigation.html.erb
  <a>
    <%= link_to 'Chatroom', root_path, class: "item"%>
  </a>
  <a class="item">
    Messages
  </a>
  <a>
    <%= link_to 'Login', login_path, class: "item" %>
  </a>
  <div class="right menu">
    <a class="ui item">
      Logout
    </a>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AllAboutUniverseRtc</title>
    <%= favicon_link_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="ui small inverted menu">
      <div class="ui container">
        <%= link_to 'Chatroom', root_path, class: "item" %>
        <% if !logged_in? %>
            <%= link_to 'Sign Up', signup_path, class: "item" %>
        <%end%>
        <div class="right menu">
          <div class="ui simple dropdown item">
            Account <i class="dropdown icon"></i>
            <div class="menu">
            <% if logged_in? %>
              <%= link_to 'Log out', logout_path, method: :delete, class: "item" %>
              <%else%>
              <%= link_to 'Login', login_path, class: "item" %>
              <%end%>
              
            </div>
          </div>
          <% if !logged_in? %>
          <div class="item">
          <%= link_to "log in" , login_path, class: "ui primary button" %>
          </div>
          <%end%>
        </div>
      </div>
    </div>
<div class="ui container">
<%= render 'layouts/messages'%>
    <%= yield %>

    <div class="ui inverted vertical center aligned footer segment nice">
    <div class="ui container">
        Real-Chat    All Rights Reserved
    </div>
</div>
    </div>


  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
              <div class="content">
                <div class="summary">

                <em><%= message.user.username %></em>: <%= message.body %>
                </div>
                </div>
                </div>

app/views/pages/home.html.erb
<h4 class="ui center aligned huge icon header">
  <i class="circular yellow coffee icon"></i>
  <font color=" yellow">Say Something</font>
</h4>

<div class="ui two column very relaxed stackable grid grid">
<div class="twelve wide column">
<div class="ui fluid raised card chatbox">
  <div class="content" id="scroll">
  <div class="ui large feed" id="mess">
 <%= render @messages %>
  </div>
</div>
<div class="extra content">
<%= form_for(@message, html: {class: "ui reply form", role: "form"}, url: message_path, remote: true) do |f| %>
    <div class="field">
      <div class="ui fluid icon input">
      <%= f.text_field :body %>
      <%= f.button '<i class="bordered inverted orange edit icon"></i>'.html_safe %>
    </div>
    </div>
  <% end %>
  </div>
</div>
</div>


<div class="four wide column">
<div class="ui fluid raised card chatbox1">
  <div class="column">
    <div class="ui segment">
<div class="ui centered fluid raised card">
  <div class="image">
    <%= image_tag "b0925ebe47af875f8ee18779216573df.jpg" %>
  </div>
</div>
</div>
</div>

</div>

</div>
</div>
</div>
</div>

app/views/users/new.html.erb
<%= form_for(:user, html: {class: "ui form", role: "form"}, url: signup_path) do |f| %>
  <div class="field">
    <%= f.label :username, class: "ui yellow label" %>
    <%= f.text_field :username, placeholder: "Enter a Username" %>
  </div>
  <div class="field">
    <%= f.label :password, class: "ui yellow label" %>
    <%= f.password_field :password, placeholder: "Enter your password" %>
  </div>
  
  <%= f.submit "sign Up", class: "ui button" %>
<%end%>